# Generated by Django 4.2.18 on 2025-06-04 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board_home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('student', '학부생'), ('professor', '교수')], default='student', max_length=20),
        ),
    ]
